### ISSUE TITLE
Add a sortable high score board

### ISSUE THREAD

**Issue by kmitche9** [rmcgraw23/TeamMSpaceInvaders#12]
Add a high score board that will hold the top 10 high scores, and that is sortable by multiple parameters.

**Comment by kmitche9** [comment]
I added a HighScore class, a HighScoreBoard class, and 2 comparer classes for the high score board. I also added created a basic UI and created the CodeBehind & ViewModel classes. Everything still needs to be implemented.

**Comment by rmcgraw23** [comment]
I added implementation for the high score, sorting the score board and adding a player to the board.
